export const GET_DIET_LIST  = 'GET_DIET_LIST';
export const GET_DIET_LIST_REQUEST  = 'GET_DIET_LIST_REQUEST';
export const GET_DIET_LIST_SUCCESS  = 'GET_DIET_LIST_SUCCESS';
export const GET_DIET_LIST_FAIL  = 'GET_DIET_LIST_FAIL';