export const GET_DIET_LIST  = 'GET_DIET_LIST';
export const GET_DIET_LIST_REQUEST  = 'GET_DIET_LIST_REQUEST';
export const GET_DIET_LIST_SUCCESS  = 'GET_DIET_LIST_SUCCESS';
export const GET_DIET_LIST_FAIL  = 'GET_DIET_LIST_FAIL';

export const GET_DIET = 'GET_DIET';
export const GET_DIET_REQUEST = 'GET_DIET_REQUEST';
export const GET_DIET_SUCCESS  = 'GET_DIET_SUCCESS';
export const GET_DIET_FAIL  = 'GET_DIET__FAIL';

export const GET_FOOD_LIST = 'GET_FOOD_LIST';
export const GET_FOOD_LIST_REQUEST = 'GET_FOOD_LIST_REQUEST';
export const GET_FOOD_LIST_SUCCESS = 'GET_FOOD_LIST_SUCCESS';
export const GET_FOOD_LIST_FAIL = 'GET_FOOD_LIST_FAIL';

export const SAVE_FOOD = 'SAVE_FOOD';
export const SAVE_FOOD_REQUEST = 'SAVE_FOOD_REQUEST';
export const SAVE_FOOD_SUCCESS = 'SAVE_FOOD_SUCCESS';
export const SAVE_FOOD_FAIL = 'SAVE_FOOD_FAIL';

export const REMOVE_FOOD = 'REMOVE_FOOD';
export const REMOVE_FOOD_REQUEST = 'REMOVE_FOOD_REQUEST';
export const REMOVE_FOOD_SUCCESS = 'REMOVE_FOOD_SUCCESS';
export const REMOVE_FOOD_FAIL = 'REMOVE_FOOD_FAIL';

export const GET_RECEIPT_LIST = 'GET_RECEIPT_LIST';
export const GET_RECEIPT_LIST_REQUEST = 'GET_RECEIPT_LIST_REQUEST';
export const GET_RECEIPT_LIST_SUCCESS = 'GET_RECEIPT_LIST_SUCCESS';
export const GET_RECEIPT_LIST_FAIL = 'GET_RECEIPT_LIST_FAIL';

export const SAVE_RECEIPT = 'SAVE_RECEIPT';
export const SAVE_RECEIPT_REQUEST = 'SAVE_RECEIPT_REQUEST';
export const SAVE_RECEIPT_SUCCESS = 'SAVE_RECEIPT_SUCCESS';
export const SAVE_RECEIPT_FAIL = 'SAVE_RECEIPT_FAIL';

export const REMOVE_RECEIPT = 'REMOVE_RECEIPT';
export const REMOVE_RECEIPT_REQUEST = 'REMOVE_RECEIPT_REQUEST';
export const REMOVE_RECEIPT_SUCCESS = 'REMOVE_RECEIPT_SUCCESS';
export const REMOVE_RECEIPT_FAIL = 'REMOVE_RECEIPT_FAIL';