export const GET_DIET_LIST  = 'GET_DIET_LIST';
export const GET_DIET_LIST_REQUEST  = 'GET_DIET_LIST_REQUEST';
export const GET_DIET_LIST_SUCCESS  = 'GET_DIET_LIST_SUCCESS';
export const GET_DIET_LIST_FAIL  = 'GET_DIET_LIST_FAIL';

export const GET_DIET = 'GET_DIET';
export const GET_DIET_REQUEST = 'GET_DIET_REQUEST';
export const GET_DIET_SUCCESS  = 'GET_DIET_SUCCESS';
export const GET_DIET_FAIL  = 'GET_DIET_FAIL';

export const GET_FOOD_LIST = 'GET_FOOD_LIST';
export const GET_FOOD_LIST_REQUEST = 'GET_FOOD_LIST_REQUEST';
export const GET_FOOD_LIST_SUCCESS = 'GET_FOOD_LIST_SUCCESS';
export const GET_FOOD_LIST_FAIL = 'GET_FOOD_LIST_FAIL';

export const SAVE_FOOD = 'SAVE_FOOD';
export const SAVE_FOOD_REQUEST = 'SAVE_FOOD_REQUEST';
export const SAVE_FOOD_SUCCESS = 'SAVE_FOOD_SUCCESS';
export const SAVE_FOOD_FAIL = 'SAVE_FOOD_FAIL';

export const REMOVE_FOOD = 'REMOVE_FOOD';
export const REMOVE_FOOD_REQUEST = 'REMOVE_FOOD_REQUEST';
export const REMOVE_FOOD_SUCCESS = 'REMOVE_FOOD_SUCCESS';
export const REMOVE_FOOD_FAIL = 'REMOVE_FOOD_FAIL';

export const GET_RECIPE_LIST = 'GET_RECIPE_LIST';
export const GET_RECIPE_LIST_REQUEST = 'GET_RECIPE_LIST_REQUEST';
export const GET_RECIPE_LIST_SUCCESS = 'GET_RECIPE_LIST_SUCCESS';
export const GET_RECIPE_LIST_FAIL = 'GET_RECIPE_LIST_FAIL';

export const SAVE_RECIPE = 'SAVE_RECIPE';
export const SAVE_RECIPE_REQUEST = 'SAVE_RECIPE_REQUEST';
export const SAVE_RECIPE_SUCCESS = 'SAVE_RECIPE_SUCCESS';
export const SAVE_RECIPE_FAIL = 'SAVE_RECIPE_FAIL';

export const REMOVE_RECIPE = 'REMOVE_RECIPE';
export const REMOVE_RECIPE_REQUEST = 'REMOVE_RECIPE_REQUEST';
export const REMOVE_RECIPE_SUCCESS = 'REMOVE_RECIPE_SUCCESS';
export const REMOVE_RECIPE_FAIL = 'REMOVE_RECIPE_FAIL';

export const GET_DIET_SCHEDULE = 'GET_DIET_SCHEDULE';
export const GET_DIET_SCHEDULE_REQUEST = 'GET_DIET_SCHEDULE_REQUEST';
export const GET_DIET_SCHEDULE_SUCCESS  = 'GET_DIET_SCHEDULE_SUCCESS';
export const GET_DIET_SCHEDULE_FAIL  = 'GET_DIET_SCHEDULE_FAIL';

export const SAVE_DIET_SCHEDULE = 'SAVE_DIET_SCHEDULE';
export const SAVE_DIET_SCHEDULE_REQUEST = 'SAVE_DIET_SCHEDULE_REQUEST';
export const SAVE_DIET_SCHEDULE_SUCCESS  = 'SAVE_DIET_SCHEDULE_SUCCESS';
export const SAVE_DIET_SCHEDULE_FAIL  = 'SAVE_DIET_SCHEDULE_FAIL';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';